#!/usr/bin/env bash

set -eux -o pipefail

here=$(cd "$(dirname "$0")" && pwd)

"${here}/cluster/bootstrap"

# XXX Find a better way to ensure Traefik CRDs are recognised.
sleep 5
"${here}/argocd/bootstrap"
