#!/usr/bin/env bash

set -eux -o pipefail

kubectl apply -f - << EOT
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
EOT

here=$(cd "$(dirname "$0")" && pwd)
kustomize build "$here" | kubectl apply -f -
